###############################################################################
#
#    server Config section
#
###############################################################################
server:
  recharege_api: "http://127.0.0.1:4000"
  timer: 10

###############################################################################
#
#    ethereum Config section
#
###############################################################################
ethereum:
  host: https://mainnet.infura.io/1UoO4I
  # blocknum: 6298769 
  # blocknum: 6346180
  blocknum: 6359745
  # token_addr: "0xddb5bfae38ce17f3ad300dd635f30acbcc275287"
  token_addr: "0xcba8162778e6a3eba60e1cf7c012b327340bd05d"  
  to_addr: "0cf0698955123303a9a36ce470552c8d10ee6198"

###############################################################################
#
#    mongo Config section
#
###############################################################################
mongo:
  host: "127.0.0.1:27017"
  db: "ethereum"
  block: "block"
  token: "sinoc"

